version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  catering-service:
    image: vinodjagwani/catering-service
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    environment:
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_DATABASE=catering_db